name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install dependencies for scripts
      - name: Install scripts dependencies
        working-directory: ./scripts
        run: npm ci

      # Install dependencies for UI
      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      # Install dependencies for Desktop
      - name: Install Desktop dependencies
        working-directory: ./desktop
        run: npm ci

      # Rename .env.example to .env for Desktop
      - name: Setup Desktop .env
        working-directory: ./desktop
        run: mv .env.example .env

      # Run the build
      - name: Build for Linux
        run: node ./scripts/build.js --platform=linux
