on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies for scripts
      - name: Install scripts dependencies
        working-directory: ./scripts
        run: npm ci

      # Step 3: Install dependencies for UI
      - name: Install UI dependencies
        working-directory: ./ui
        run: npm ci

      # Step 4: Install dependencies for Desktop
      - name: Install Desktop dependencies
        working-directory: ./desktop
        run: npm ci

      - name: Ensure binman-linux is executable
        working-directory: ./desktop
        run: |
          BINMAN_PATH="./node_modules/umbr-binman/bin/binman-linux"
          if test -x "$BINMAN_PATH"; then
            echo "$BINMAN_PATH is already executable. Skipping chmod."
          else
            echo "$BINMAN_PATH is not executable. Applying chmod +x."
            chmod +x "$BINMAN_PATH"
          fi

      # Step 6: Rename .env.example to .env for Desktop
      - name: Setup Desktop .env
        working-directory: ./desktop
        run: mv .env.example .env

      # Step 7: Run the build script
      - name: Build for Linux
        run: node ./scripts/build.js --platform=linux