name: Dev Build Sanity Test for Fluf

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dev-build-sanity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install UI dependencies
        run: npm i
        working-directory: ./ui

      - name: Install Desktop dependencies
        run: npm i
        working-directory: ./desktop

      - name: Install Sanity Test dependencies
        run: npm i
        working-directory: ./test/sanity

      - name: Install rollup for sanity
        run: npm i @rollup/rollup-linux-x64-gnu
        working-directory: ./test/sanity

      - name: Build desktop dev
        run: npm run build:dev
        working-directory: ./desktop

      - name: Run Playwright Sanity Tests
        run: npx playwright test
        working-directory: ./test/sanity
